name: Basic upload-evidence-action

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run upload-evidence-action
        uses: bridgedai/upload-evidence-action@v1
        with:
          mode: mock
